# -*- coding: utf-8 -*-
"""
データベース接続とスキーマ初期化
"""

import os
import sqlite3
from urllib.parse import urlparse

# ---- psycopg2 の有無 ----
try:
    import psycopg2
except Exception:
    psycopg2 = None


def _is_pg(conn) -> bool:
    """PostgreSQL/SQLite 判定"""
    return conn.__class__.__module__.startswith("psycopg2")


def _sql(conn, text: str) -> str:
    """プレースホルダ統一（PostgreSQL: %s ／ SQLite: ?）"""
    return text if _is_pg(conn) else text.replace("%s", "?")


def get_db_connection():
    """
    データベース接続を返す（get_dbのエイリアス）
    """
    return get_db()


def get_db():
    """
    優先順位：
      1) .env/環境変数の DATABASE_URL
      2) SQLite (database/teikan_sakusei.db)
    戻り値: DB接続オブジェクト
    """
    db_url = os.environ.get("DATABASE_URL")

    # --- Try PostgreSQL ---
    if db_url and psycopg2:
        try:
            url = urlparse(db_url)
            sslmode = "disable" if (url.hostname in ("localhost", "127.0.0.1")) else "require"
            conn = psycopg2.connect(
                dbname=url.path[1:],
                user=url.username,
                password=url.password,
                host=url.hostname,
                port=url.port,
                sslmode=sslmode,
                application_name="teikan_sakusei_app"
            )
            conn.autocommit = True
            print(f"✅ PostgreSQL 接続成功: {url.hostname}:{url.port}/{url.path[1:]}")
            init_schema(conn)           # スキーマ自動作成
            return conn
        except Exception as e:
            print(f"⚠️ PostgreSQL接続失敗 → SQLiteへフォールバック: {e}")

    # --- SQLite フォールバック ---
    os.makedirs("database", exist_ok=True)
    conn = sqlite3.connect("database/teikan_sakusei.db", detect_types=sqlite3.PARSE_DECLTYPES)
    conn.row_factory = sqlite3.Row
    print("⚠️ SQLite にフォールバック: database/teikan_sakusei.db")
    init_schema(conn)
    return conn


def init_schema(conn):
    """
    PostgreSQL / SQLite 共通のスキーマ初期化
    - T_管理者（system_admin / admin ログイン用）
    - T_テナント（マルチテナント対応）
    """
    cur = conn.cursor()

    # ---- T_テナント ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_テナント"(
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            名称        TEXT NOT NULL,
            slug        TEXT UNIQUE NOT NULL,
            有効        INTEGER DEFAULT 1,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_テナント"(
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            名称        TEXT NOT NULL,
            slug        TEXT UNIQUE NOT NULL,
            有効        INTEGER DEFAULT 1,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_管理者 ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_管理者"(
            id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            login_id         TEXT UNIQUE NOT NULL,
            name             TEXT NOT NULL,
            password_hash    TEXT NOT NULL,
            role             TEXT DEFAULT 'admin',
            tenant_id        INTEGER,
            active           INTEGER DEFAULT 1,
            is_owner         INTEGER DEFAULT 0,
            can_manage_admins INTEGER DEFAULT 0,
            created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_管理者"(
            id               INTEGER PRIMARY KEY AUTOINCREMENT,
            login_id         TEXT UNIQUE NOT NULL,
            name             TEXT NOT NULL,
            password_hash    TEXT NOT NULL,
            role             TEXT DEFAULT 'admin',
            tenant_id        INTEGER,
            active           INTEGER DEFAULT 1,
            is_owner         INTEGER DEFAULT 0,
            can_manage_admins INTEGER DEFAULT 0,
            created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    if not _is_pg(conn):
        conn.commit()
