# -*- coding: utf-8 -*-
"""
データベース接続とスキーマ初期化
"""

import os
import sqlite3
from urllib.parse import urlparse

# ---- psycopg2 の有無 ----
try:
    import psycopg2
except Exception:
    psycopg2 = None


def _is_pg(conn) -> bool:
    """PostgreSQL/SQLite 判定"""
    return conn.__class__.__module__.startswith("psycopg2")


def _sql(conn, text: str) -> str:
    """プレースホルダ統一（PostgreSQL: %s ／ SQLite: ?）"""
    return text if _is_pg(conn) else text.replace("%s", "?")


def get_db_connection():
    """
    データベース接続を返す（get_dbのエイリアス）
    """
    return get_db()


def get_db():
    """
    優先順位：
      1) .env/環境変数の DATABASE_URL
      2) SQLite (database/teikan_sakusei.db)
    戻り値: DB接続オブジェクト
    """
    db_url = os.environ.get("DATABASE_URL")

    # --- Try PostgreSQL ---
    if db_url and psycopg2:
        try:
            url = urlparse(db_url)
            sslmode = "disable" if (url.hostname in ("localhost", "127.0.0.1")) else "require"
            conn = psycopg2.connect(
                dbname=url.path[1:],
                user=url.username,
                password=url.password,
                host=url.hostname,
                port=url.port,
                sslmode=sslmode,
                application_name="teikan_sakusei_app"
            )
            conn.autocommit = True
            print(f"✅ PostgreSQL 接続成功: {url.hostname}:{url.port}/{url.path[1:]}")
            init_schema(conn)           # スキーマ自動作成
            return conn
        except Exception as e:
            print(f"⚠️ PostgreSQL接続失敗 → SQLiteへフォールバック: {e}")

    # --- SQLite フォールバック ---
    os.makedirs("database", exist_ok=True)
    conn = sqlite3.connect("database/teikan_sakusei.db", detect_types=sqlite3.PARSE_DECLTYPES)
    conn.row_factory = sqlite3.Row
    print("⚠️ SQLite にフォールバック: database/teikan_sakusei.db")
    init_schema(conn)
    return conn


def init_schema(conn):
    """
    PostgreSQL / SQLite 共通のスキーマ初期化
    - T_管理者（system_admin / admin ログイン用）
    - T_テナント（マルチテナント対応）
    """
    cur = conn.cursor()

    # ---- T_テナント ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_テナント"(
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            名称        TEXT NOT NULL,
            slug        TEXT UNIQUE NOT NULL,
            有効        INTEGER DEFAULT 1,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_テナント"(
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            名称        TEXT NOT NULL,
            slug        TEXT UNIQUE NOT NULL,
            有効        INTEGER DEFAULT 1,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_管理者 ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_管理者"(
            id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            login_id         TEXT UNIQUE NOT NULL,
            name             TEXT NOT NULL,
            password_hash    TEXT NOT NULL,
            role             TEXT DEFAULT 'admin',
            tenant_id        INTEGER,
            email            TEXT,
            active           INTEGER DEFAULT 1,
            is_owner         INTEGER DEFAULT 0,
            can_manage_admins INTEGER DEFAULT 0,
            created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_管理者"(
            id               INTEGER PRIMARY KEY AUTOINCREMENT,
            login_id         TEXT UNIQUE NOT NULL,
            name             TEXT NOT NULL,
            password_hash    TEXT NOT NULL,
            role             TEXT DEFAULT 'admin',
            tenant_id        INTEGER,
            email            TEXT,
            active           INTEGER DEFAULT 1,
            is_owner         INTEGER DEFAULT 0,
            can_manage_admins INTEGER DEFAULT 0,
            created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_定款 ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_定款"(
            id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id               INTEGER,
            created_by              INTEGER,
            会社名                  TEXT NOT NULL,
            会社名_英語             TEXT,
            本店所在地_都道府県     TEXT NOT NULL,
            本店所在地_市区町村     TEXT NOT NULL,
            本店所在地_番地         TEXT NOT NULL,
            本店所在地_建物名       TEXT,
            事業年度_決算月         INTEGER NOT NULL,
            発行可能株式総数        INTEGER NOT NULL,
            設立時発行株式数        INTEGER NOT NULL,
            一株の金額              INTEGER NOT NULL,
            資本金                  INTEGER NOT NULL,
            譲渡制限                INTEGER DEFAULT 1,
            承認機関                TEXT DEFAULT '株主総会',
            取締役の人数            INTEGER DEFAULT 1,
            取締役会設置            INTEGER DEFAULT 0,
            監査役設置              INTEGER DEFAULT 0,
            会計参与設置            INTEGER DEFAULT 0,
            公告方法                TEXT DEFAULT '官報',
            ステータス              TEXT DEFAULT 'draft',
            created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_定款"(
            id                      INTEGER PRIMARY KEY AUTOINCREMENT,
            tenant_id               INTEGER,
            created_by              INTEGER,
            会社名                  TEXT NOT NULL,
            会社名_英語             TEXT,
            本店所在地_都道府県     TEXT NOT NULL,
            本店所在地_市区町村     TEXT NOT NULL,
            本店所在地_番地         TEXT NOT NULL,
            本店所在地_建物名       TEXT,
            事業年度_決算月         INTEGER NOT NULL,
            発行可能株式総数        INTEGER NOT NULL,
            設立時発行株式数        INTEGER NOT NULL,
            一株の金額              INTEGER NOT NULL,
            資本金                  INTEGER NOT NULL,
            譲渡制限                INTEGER DEFAULT 1,
            承認機関                TEXT DEFAULT '株主総会',
            取締役の人数            INTEGER DEFAULT 1,
            取締役会設置            INTEGER DEFAULT 0,
            監査役設置              INTEGER DEFAULT 0,
            会計参与設置            INTEGER DEFAULT 0,
            公告方法                TEXT DEFAULT '官報',
            ステータス              TEXT DEFAULT 'draft',
            created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_事業目的 ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_事業目的"(
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            定款_id     INTEGER NOT NULL,
            順序        INTEGER NOT NULL,
            目的        TEXT NOT NULL,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_事業目的"(
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            定款_id     INTEGER NOT NULL,
            順序        INTEGER NOT NULL,
            目的        TEXT NOT NULL,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_発起人 ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_発起人"(
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            定款_id     INTEGER NOT NULL,
            氏名        TEXT NOT NULL,
            住所        TEXT NOT NULL,
            引受株式数  INTEGER NOT NULL,
            出資金額    INTEGER NOT NULL,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_発起人"(
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            定款_id     INTEGER NOT NULL,
            氏名        TEXT NOT NULL,
            住所        TEXT NOT NULL,
            引受株式数  INTEGER NOT NULL,
            出資金額    INTEGER NOT NULL,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_従業員 ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_従業員"(
            id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email         TEXT UNIQUE NOT NULL,
            login_id      TEXT UNIQUE NOT NULL,
            name          TEXT NOT NULL,
            password_hash TEXT,
            tenant_id     INTEGER,
            role          TEXT DEFAULT 'employee',
            created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_従業員"(
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            email         TEXT UNIQUE NOT NULL,
            login_id      TEXT UNIQUE NOT NULL,
            name          TEXT NOT NULL,
            password_hash TEXT,
            tenant_id     INTEGER,
            role          TEXT DEFAULT 'employee',
            created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_店舗 ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_店舗"(
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id   INTEGER NOT NULL,
            名称        TEXT NOT NULL,
            slug        TEXT NOT NULL,
            有効        INTEGER DEFAULT 1,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(tenant_id, slug)
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_店舗"(
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            tenant_id   INTEGER NOT NULL,
            名称        TEXT NOT NULL,
            slug        TEXT NOT NULL,
            有効        INTEGER DEFAULT 1,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(tenant_id, slug)
        )''')

    # ---- T_テナント管理者_テナント (多対多関係) ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_テナント管理者_テナント"(
            id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_admin_id     INTEGER NOT NULL,
            tenant_id           INTEGER NOT NULL,
            created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(tenant_admin_id, tenant_id)
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_テナント管理者_テナント"(
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            tenant_admin_id     INTEGER NOT NULL,
            tenant_id           INTEGER NOT NULL,
            created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(tenant_admin_id, tenant_id)
        )''')

    # ---- T_管理者_店舗 (多対多関係) ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_管理者_店舗"(
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            admin_id    INTEGER NOT NULL,
            store_id    INTEGER NOT NULL,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(admin_id, store_id)
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_管理者_店舗"(
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            admin_id    INTEGER NOT NULL,
            store_id    INTEGER NOT NULL,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(admin_id, store_id)
        )''')

    # ---- T_従業員_店舗 (多対多関係) ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_従業員_店舗"(
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id     INTEGER NOT NULL,
            store_id        INTEGER NOT NULL,
            created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(employee_id, store_id)
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_従業員_店舗"(
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            employee_id     INTEGER NOT NULL,
            store_id        INTEGER NOT NULL,
            created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(employee_id, store_id)
        )''')

    if not _is_pg(conn):
        conn.commit()
